"""В модель Client добавлены поля latitude, longitude

Revision ID: 2a3e82180d4c
Revises: 5a0716794b4e
Create Date: 2024-10-30 19:49:10.387458

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a3e82180d4c'
down_revision: Union[str, None] = '5a0716794b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('clients', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'longitude')
    op.drop_column('clients', 'latitude')
    # ### end Alembic commands ###
