"""Added hashed_password field to Client model

Revision ID: 418d4ea582fa
Revises: 33b21d7f2817
Create Date: 2024-10-29 16:29:04.764299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418d4ea582fa'
down_revision: Union[str, None] = '33b21d7f2817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_id', table_name='clients')
    op.create_unique_constraint(None, 'clients', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='unique')
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.drop_column('clients', 'hashed_password')
    # ### end Alembic commands ###
