"""Созданы таблицы clients и match

Revision ID: 59e628f1caf5
Revises: 51c1eadeeefd
Create Date: 2024-10-30 00:17:22.633719

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '59e628f1caf5'
down_revision: Union[str, None] = '51c1eadeeefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('avatar', sa.String(), nullable=True),
        sa.Column(
            'gender', sa.Enum('male', 'female', name='genderenum'), nullable=False
        ),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_index(
        op.f('ix_clients_first_name'), 'clients', ['first_name'], unique=False
    )
    op.create_index(
        op.f('ix_clients_last_name'), 'clients', ['last_name'], unique=False
    )
    op.create_table(
        'match',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_index(op.f('ix_clients_last_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_first_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
