"""В таблицу match добавлено поле create_at

Revision ID: 7ea8a24fc234
Revises: 59e628f1caf5
Create Date: 2024-10-30 10:47:44.328559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea8a24fc234'
down_revision: Union[str, None] = '59e628f1caf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'created_at')
    # ### end Alembic commands ###
